// <auto-generated />
using System;
using Demo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260204193128_YESVE")]
    partial class YESVE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CPUId")
                        .HasColumnType("int");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("GPUId")
                        .HasColumnType("int");

                    b.Property<int>("MotherboardId")
                        .HasColumnType("int");

                    b.Property<int>("PowerSupplyId")
                        .HasColumnType("int");

                    b.Property<int>("RAMId")
                        .HasColumnType("int");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CPUId");

                    b.HasIndex("CaseId");

                    b.HasIndex("GPUId");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("PowerSupplyId");

                    b.HasIndex("RAMId");

                    b.HasIndex("StorageId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("Demo.Models.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<float>("ClockSpeedGHz")
                        .HasColumnType("real");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CPUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "",
                            ClockSpeedGHz = 2.5f,
                            Cores = 6,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9049),
                            IsActive = true,
                            Name = "Intel Core i5-12400F",
                            Price = 160m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "",
                            ClockSpeedGHz = 3.4f,
                            Cores = 16,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9056),
                            IsActive = true,
                            Name = "Intel Core i7-13700K",
                            Price = 420m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "",
                            ClockSpeedGHz = 3.5f,
                            Cores = 6,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9058),
                            IsActive = true,
                            Name = "AMD Ryzen 5 5600",
                            Price = 140m,
                            Socket = "AM4"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "",
                            ClockSpeedGHz = 4.2f,
                            Cores = 8,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9059),
                            IsActive = true,
                            Name = "AMD Ryzen 7 7800X3D",
                            Price = 400m,
                            Socket = "AM5"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "",
                            ClockSpeedGHz = 3.2f,
                            Cores = 24,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9060),
                            IsActive = true,
                            Name = "Intel Core i9-14900K",
                            Price = 600m,
                            Socket = "LGA1700"
                        });
                });

            modelBuilder.Entity("Demo.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "",
                            Color = "White",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9322),
                            FormFactor = "ATX",
                            IsActive = true,
                            Name = "NZXT H510",
                            Price = 80m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "",
                            Color = "Black",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9323),
                            FormFactor = "ATX",
                            IsActive = true,
                            Name = "Lian Li Lancool II Mesh",
                            Price = 100m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "",
                            Color = "Black",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9325),
                            FormFactor = "Mini-ITX",
                            IsActive = true,
                            Name = "Cooler Master NR200",
                            Price = 90m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "",
                            Color = "Black",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9326),
                            FormFactor = "ATX",
                            IsActive = true,
                            Name = "Fractal Design Meshify 2",
                            Price = 140m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "",
                            Color = "White",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9327),
                            FormFactor = "ATX",
                            IsActive = true,
                            Name = "Corsair 4000D Airflow",
                            Price = 120m
                        });
                });

            modelBuilder.Entity("Demo.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Demo.Models.GPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MemoryGB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("GPUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "",
                            Chipset = "Ada Lovelace",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9199),
                            IsActive = true,
                            MemoryGB = 8,
                            Name = "NVIDIA RTX 4060",
                            Price = 300m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "",
                            Chipset = "Ada Lovelace",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9201),
                            IsActive = true,
                            MemoryGB = 12,
                            Name = "NVIDIA RTX 4070",
                            Price = 550m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "",
                            Chipset = "RDNA 3",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9202),
                            IsActive = true,
                            MemoryGB = 8,
                            Name = "AMD Radeon RX 7600",
                            Price = 270m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "",
                            Chipset = "RDNA 3",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9203),
                            IsActive = true,
                            MemoryGB = 20,
                            Name = "AMD Radeon RX 7900 XT",
                            Price = 750m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "",
                            Chipset = "Ada Lovelace",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9204),
                            IsActive = true,
                            MemoryGB = 24,
                            Name = "NVIDIA RTX 4090",
                            Price = 1600m
                        });
                });

            modelBuilder.Entity("Demo.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Motherboards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9225),
                            FormFactor = "Micro-ATX",
                            IsActive = true,
                            Name = "ASUS TUF Gaming B660M-PLUS",
                            Price = 150m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9227),
                            FormFactor = "ATX",
                            IsActive = true,
                            Name = "MSI MAG B550 TOMAHAWK",
                            Price = 180m,
                            Socket = "AM4"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9229),
                            FormFactor = "ATX",
                            IsActive = true,
                            Name = "Gigabyte X670 AORUS ELITE",
                            Price = 230m,
                            Socket = "AM5"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9230),
                            FormFactor = "ATX",
                            IsActive = true,
                            Name = "ASRock Z790 Steel Legend",
                            Price = 220m,
                            Socket = "LGA1700"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9231),
                            FormFactor = "ATX",
                            IsActive = true,
                            Name = "MSI PRO B650-P",
                            Price = 200m,
                            Socket = "AM5"
                        });
                });

            modelBuilder.Entity("Demo.Models.PowerSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Efficiency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PowerSupplies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9297),
                            Efficiency = "80+ Gold",
                            IsActive = true,
                            Name = "Corsair RM750e",
                            Price = 100m,
                            Wattage = 750
                        },
                        new
                        {
                            Id = 2,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9299),
                            Efficiency = "80+ Bronze",
                            IsActive = true,
                            Name = "EVGA 600 BR",
                            Price = 50m,
                            Wattage = 600
                        },
                        new
                        {
                            Id = 3,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9300),
                            Efficiency = "80+ Gold",
                            IsActive = true,
                            Name = "Seasonic Focus GX-850",
                            Price = 120m,
                            Wattage = 850
                        },
                        new
                        {
                            Id = 4,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9301),
                            Efficiency = "80+ Bronze",
                            IsActive = true,
                            Name = "Cooler Master MWE 650",
                            Price = 70m,
                            Wattage = 650
                        },
                        new
                        {
                            Id = 5,
                            Brand = "",
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9302),
                            Efficiency = "80+ Platinum",
                            IsActive = true,
                            Name = "ASUS ROG Loki 1000W",
                            Price = 250m,
                            Wattage = 1000
                        });
                });

            modelBuilder.Entity("Demo.Models.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CapacityGB")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpeedMHz")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RAMs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "",
                            CapacityGB = 16,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9249),
                            IsActive = true,
                            Name = "Corsair Vengeance LPX 16GB",
                            Price = 50m,
                            SpeedMHz = 3200,
                            Type = "DDR4"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "",
                            CapacityGB = 32,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9250),
                            IsActive = true,
                            Name = "G.Skill Trident Z5 32GB",
                            Price = 160m,
                            SpeedMHz = 6000,
                            Type = "DDR5"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "",
                            CapacityGB = 16,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9252),
                            IsActive = true,
                            Name = "Kingston Fury Beast 16GB",
                            Price = 55m,
                            SpeedMHz = 3600,
                            Type = "DDR4"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "",
                            CapacityGB = 32,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9253),
                            IsActive = true,
                            Name = "Crucial DDR5 32GB",
                            Price = 140m,
                            SpeedMHz = 5600,
                            Type = "DDR5"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "",
                            CapacityGB = 16,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9254),
                            IsActive = true,
                            Name = "TeamGroup T-Force Delta RGB 16GB",
                            Price = 60m,
                            SpeedMHz = 3200,
                            Type = "DDR4"
                        });
                });

            modelBuilder.Entity("Demo.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CapacityGB")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "",
                            CapacityGB = 1000,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9272),
                            IsActive = true,
                            Name = "Samsung 970 EVO Plus",
                            Price = 90m,
                            Type = "NVMe SSD"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "",
                            CapacityGB = 1000,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9274),
                            IsActive = true,
                            Name = "Crucial MX500",
                            Price = 70m,
                            Type = "SSD"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "",
                            CapacityGB = 500,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9275),
                            IsActive = true,
                            Name = "WD Blue SN570",
                            Price = 40m,
                            Type = "NVMe SSD"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "",
                            CapacityGB = 2000,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9276),
                            IsActive = true,
                            Name = "Seagate Barracuda",
                            Price = 60m,
                            Type = "HDD"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "",
                            CapacityGB = 2000,
                            CreatedUtc = new DateTime(2026, 2, 4, 19, 31, 27, 203, DateTimeKind.Utc).AddTicks(9276),
                            IsActive = true,
                            Name = "Kingston KC3000",
                            Price = 160m,
                            Type = "NVMe SSD"
                        });
                });

            modelBuilder.Entity("Demo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Demo.Models.Build", b =>
                {
                    b.HasOne("Demo.Models.CPU", "CPU")
                        .WithMany()
                        .HasForeignKey("CPUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo.Models.GPU", "GPU")
                        .WithMany()
                        .HasForeignKey("GPUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo.Models.Motherboard", "Motherboard")
                        .WithMany()
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo.Models.PowerSupply", "PowerSupply")
                        .WithMany()
                        .HasForeignKey("PowerSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo.Models.RAM", "RAM")
                        .WithMany()
                        .HasForeignKey("RAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo.Models.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CPU");

                    b.Navigation("Case");

                    b.Navigation("GPU");

                    b.Navigation("Motherboard");

                    b.Navigation("PowerSupply");

                    b.Navigation("RAM");

                    b.Navigation("Storage");
                });
#pragma warning restore 612, 618
        }
    }
}
